'use strict'

export const REFRESH_CHAT_DOING = 'REFRESH_CHAT_DOING';
export const REFRESH_CHAT_SUC = 'REFRESH_CHAT_SUC';
export const REFRESH_CHAT_FAIL = 'REFRESH_CHAT_FAIL';
export const REFRESH_CHAT_ERROR = 'REFRESH_CHAT_ERROR';

export const LOAD_CHAT_DOING = 'LOAD_CHAT_DOING';
export const LOAD_CHAT_SUC = 'LOAD_CHAT_SUC';
export const LOAD_CHAT_FAIL = 'LOAD_CHAT_FAIL';
export const LOAD_CHAT_ERROR = 'LOAD_CHAT_ERROR';

export const FILTER_CHAT = 'FILTER_CHAT';