'use strict'

export const LINE_LIST_DOING = 'LINE_LIST_DOING';
export const LINE_LIST_SUC = 'LINT_LIST_SUC';
export const LINE_LIST_FAIL = 'LINE_LIST_FAIL';
export const LINE_LIST_ERROR = 'LINE_LIST_ERROR';

export const LINE_DETAIL_DOING = 'LINE_DETAIL_DOING';
export const LINE_DETAIL_SUC = 'LINE_DETAIL_SUC';
export const LINE_DETAIL_FAIL = 'LINE_DETAIL_FAIL';
export const LINE_DETAIL_ERROR = 'LINE_DETAIL_ERROR';